export const weatherLanguages = {
  "sq": "Albanian",
  "af": "Afrikaans",
  "ar": "Arabic",
  "az": "Azerbaijani",
  "eu": "Basque",
  "be": "Belarusian",
  "bg": "Bulgarian",
  "ca": "Catalan",
  "zh_cn": "Chinese Simplified",
  "zh_tw": "Chinese Traditional",
  "hr": "Croatian",
  "cz": "Czech",
  "da": "Danish",
  "nl": "Dutch",
  "en": "English",
  "fi": "Finnish",
  "fr": "French",
  "gl": "Galician",
  "de": "German",
  "el": "Greek",
  "he": "Hebrew",
  "hi": "Hindi",
  "hu": "Hungarian",
  "is": "Icelandic",
  "id": "Indonesian",
  "it": "Italian",
  "ja": "Japanese",
  "kr": "Korean",
  "ku": "Kurmanji (Kurdish)",
  "la": "Latvian",
  "lt": "Lithuanian",
  "mk": "Macedonian",
  "no": "Norwegian",
  "fa": "Persian (Farsi)",
  "pl": "Polish",
  "pt": "Portuguese",
  "pt_br": "Português Brasil",
  "ro": "Romanian",
  "ru": "Russian",
  "sr": "Serbian",
  "sk": "Slovak",
  "sl": "Slovenian",
  "es": "Spanish",
  "se": "Swedish",
  "th": "Thai",
  "tr": "Turkish",
  "ua": "Ukrainian",
  "vi": "Vietnamese",
  "zu": "Zulu",
}

export const weatherIcons = {
  "01d": "2600.png",
  "02d": "26c5.png",
  "03d": "2601.png",
  "04d": "1f327.png",
  "09d": "1f327.png",
  "10d": "1f326.png",
  "11d": "26c8.png",
  "13d": "1f328.png",
  "50d": "1f32b.png",
  "01n": "1f311.png",
  "02n": "26c5.png",
  "03n": "2601.png",
  "04n": "1f327.png",
  "09n": "1f327.png",
  "10n": "1f326.png",
  "11n": "26c8.png",
  "13n": "1f328.png",
  "50n": "1f32b.png",
}

export const dateLocales = {
  // English variants
  "en-US": "English (United States)",
  "en-GB": "English (United Kingdom)",
  "en-CA": "English (Canada)",
  "en-AU": "English (Australia)",
  "en-IN": "English (India)",

  // Europe
  "no-NO": "Norwegian (Norway)",
  "sv-SE": "Swedish (Sweden)",
  "da-DK": "Danish (Denmark)",
  "fi-FI": "Finnish (Finland)",
  "is-IS": "Icelandic (Iceland)",
  "de-DE": "German (Germany)",
  "nl-NL": "Dutch (Netherlands)",
  "fr-FR": "French (France)",
  "es-ES": "Spanish (Spain)",
  "it-IT": "Italian (Italy)",
  "pt-PT": "Portuguese (Portugal)",
  "pt-BR": "Portuguese (Brazil)",
  "pl-PL": "Polish (Poland)",
  "cs-CZ": "Czech (Czech Republic)",
  "sk-SK": "Slovak (Slovakia)",
  "hu-HU": "Hungarian (Hungary)",
  "ru-RU": "Russian (Russia)",
  "uk-UA": "Ukrainian (Ukraine)",

  // Asian
  "ja-JP": "Japanese (Japan)",
  "zh-CN": "Chinese (Simplified, China)",
  "zh-TW": "Chinese (Traditional, Taiwan)",
  "ko-KR": "Korean (South Korea)",
  "th-TH": "Thai (Thailand)",
  "hi-IN": "Hindi (India)",
  "bn-BD": "Bengali (Bangladesh)",

  // Middle East
  "ar-SA": "Arabic (Saudi Arabia)",
  "he-IL": "Hebrew (Israel)",
  "tr-TR": "Turkish (Turkey)",
  "fa-IR": "Persian (Iran)",

  // Africa
  "af-ZA": "Afrikaans (South Africa)",
  "sw-KE": "Swahili (Kenya)",

  // Americas
  "es-MX": "Spanish (Mexico)",
  "es-AR": "Spanish (Argentina)",
  "fr-CA": "French (Canada)",
  "en-NZ": "English (New Zealand)",

  // Misc
  "el-GR": "Greek (Greece)",
  "ro-RO": "Romanian (Romania)",
  "id-ID": "Indonesian (Indonesia)",
  "ms-MY": "Malay (Malaysia)",
  "vi-VN": "Vietnamese (Vietnam)",
  "ta-IN": "Tamil (India)",
}
