export const weather_languages = {
  "sq": "Albanian",
  "af": "Afrikaans",
  "ar": "Arabic",
  "az": "Azerbaijani",
  "eu": "Basque",
  "be": "Belarusian",
  "bg": "Bulgarian",
  "ca": "Catalan",
  "zh_cn": "Chinese Simplified",
  "zh_tw": "Chinese Traditional",
  "hr": "Croatian",
  "cz": "Czech",
  "da": "Danish",
  "nl": "Dutch",
  "en": "English",
  "fi": "Finnish",
  "fr": "French",
  "gl": "Galician",
  "de": "German",
  "el": "Greek",
  "he": "Hebrew",
  "hi": "Hindi",
  "hu": "Hungarian",
  "is": "Icelandic",
  "id": "Indonesian",
  "it": "Italian",
  "ja": "Japanese",
  "kr": "Korean",
  "ku": "Kurmanji (Kurdish)",
  "la": "Latvian",
  "lt": "Lithuanian",
  "mk": "Macedonian",
  "no": "Norwegian",
  "fa": "Persian (Farsi)",
  "pl": "Polish",
  "pt": "Portuguese",
  "pt_br": "Português Brasil",
  "ro": "Romanian",
  "ru": "Russian",
  "sr": "Serbian",
  "sk": "Slovak",
  "sl": "Slovenian",
  "es": "Spanish",
  "se": "Swedish",
  "th": "Thai",
  "tr": "Turkish",
  "ua": "Ukrainian",
  "vi": "Vietnamese",
  "zu": "Zulu",
}

export const wicons = {
  "01d": "2600.png",
  "02d": "26c5.png",
  "03d": "2601.png",
  "04d": "1f327.png",
  "09d": "1f327.png",
  "10d": "1f326.png",
  "11d": "26c8.png",
  "13d": "1f328.png",
  "50d": "1f32b.png",
  "01n": "1f311.png",
  "02n": "26c5.png",
  "03n": "2601.png",
  "04n": "1f327.png",
  "09n": "1f327.png",
  "10n": "1f326.png",
  "11n": "26c8.png",
  "13n": "1f328.png",
  "50n": "1f32b.png",
}
